/*
  # Create Admin Products and Remove Dropshipping

  1. Remove Dropshipping
    - Delete all dropshipping-related products
    - Clean up dropshipping tables
  
  2. Create Admin Products
    - Add 30 high-quality products owned by admin
    - Use real product images from Pexels
    - Create realistic product data across all categories
  
  3. Security
    - Maintain existing RLS policies
    - Ensure admin can manage all products
*/

-- Remove all dropshipping products and related data
DELETE FROM order_items WHERE is_dropshipped = true;
DELETE FROM products WHERE is_dropshipped = true;
DELETE FROM dropshipping_products;
DELETE FROM dropshipping_orders;
DELETE FROM dropshipping_sync_logs;
DELETE FROM dropshipping_config;

-- Get the admin user ID (assuming admin@samoku.com exists)
DO $$
DECLARE
    admin_user_id uuid;
    admin_store_id uuid;
BEGIN
    -- Get admin user
    SELECT id INTO admin_user_id
    FROM auth.users 
    WHERE email = 'admin@samoku.com'
    LIMIT 1;
    
    -- If no admin user found, create a placeholder UUID
    IF admin_user_id IS NULL THEN
        admin_user_id := '00000000-0000-0000-0000-000000000001'::uuid;
    END IF;
    
    -- Get or create admin store
    SELECT id INTO admin_store_id
    FROM stores 
    WHERE user_id = admin_user_id
    LIMIT 1;
    
    -- If no admin store found, create one
    IF admin_store_id IS NULL THEN
        INSERT INTO stores (
            id,
            user_id,
            name,
            description,
            is_approved,
            is_active,
            commission_rate
        ) VALUES (
            '550e8400-e29b-41d4-a716-446655440000'::uuid,
            admin_user_id,
            'Samoku Official Store',
            'Premium products curated by Samoku team',
            true,
            true,
            0
        );
        admin_store_id := '550e8400-e29b-41d4-a716-446655440000'::uuid;
    END IF;

    -- Insert 30 premium products across all categories
    INSERT INTO products (
        name,
        description,
        price,
        original_price,
        images,
        category,
        subcategory,
        sku,
        stock_quantity,
        owner_id,
        store_id,
        is_dropshipped,
        tags,
        specifications,
        rating,
        review_count,
        sales_count,
        is_active
    ) VALUES
    -- Electronics (8 products)
    (
        'Apple iPhone 15 Pro Max',
        'The ultimate iPhone with titanium design, advanced Pro camera system, and A17 Pro chip for exceptional performance.',
        1199.00,
        1299.00,
        ARRAY['https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'electronics',
        'smartphones',
        'SAMOKU-IP15PM-001',
        50,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['apple', 'iphone', 'smartphone', 'premium', 'titanium'],
        '{"screen_size": "6.7 inches", "storage": "256GB", "camera": "48MP Pro", "battery": "29 hours video"}'::jsonb,
        4.8,
        1247,
        523,
        true
    ),
    (
        'Samsung Galaxy S24 Ultra',
        'Revolutionary Galaxy AI features, built-in S Pen, and pro-grade camera with 200MP resolution.',
        1299.00,
        1399.00,
        ARRAY['https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'electronics',
        'smartphones',
        'SAMOKU-SGS24U-002',
        35,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['samsung', 'galaxy', 'android', 's-pen', 'ai'],
        '{"screen_size": "6.8 inches", "storage": "512GB", "camera": "200MP", "battery": "5000mAh"}'::jsonb,
        4.7,
        892,
        367,
        true
    ),
    (
        'MacBook Pro 16-inch M3 Max',
        'Ultimate laptop for professionals with M3 Max chip, stunning Liquid Retina XDR display, and all-day battery life.',
        3199.00,
        3499.00,
        ARRAY['https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'electronics',
        'laptops',
        'SAMOKU-MBP16-003',
        25,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['apple', 'macbook', 'laptop', 'm3', 'professional'],
        '{"processor": "M3 Max", "memory": "36GB", "storage": "1TB SSD", "display": "16.2-inch Liquid Retina XDR"}'::jsonb,
        4.9,
        445,
        178,
        true
    ),
    (
        'Sony WH-1000XM5 Headphones',
        'Industry-leading noise canceling wireless headphones with premium sound quality and 30-hour battery life.',
        349.00,
        399.00,
        ARRAY['https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'electronics',
        'audio',
        'SAMOKU-SONY-004',
        75,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['sony', 'headphones', 'wireless', 'noise-canceling', 'premium'],
        '{"battery": "30 hours", "weight": "250g", "connectivity": "Bluetooth 5.2", "noise_canceling": "Industry-leading"}'::jsonb,
        4.6,
        2134,
        1245,
        true
    ),
    (
        'iPad Pro 12.9-inch M2',
        'Most advanced iPad ever with M2 chip, Liquid Retina XDR display, and support for Apple Pencil and Magic Keyboard.',
        1099.00,
        1199.00,
        ARRAY['https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'electronics',
        'tablets',
        'SAMOKU-IPADPRO-005',
        40,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['apple', 'ipad', 'tablet', 'm2', 'pro'],
        '{"screen_size": "12.9 inches", "processor": "M2 chip", "storage": "256GB", "compatibility": "Apple Pencil 2"}'::jsonb,
        4.7,
        778,
        234,
        true
    ),
    (
        'Dell XPS 13 Plus',
        'Premium ultrabook with InfinityEdge display, 12th Gen Intel Core processors, and stunning design.',
        1299.00,
        1499.00,
        ARRAY['https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'electronics',
        'laptops',
        'SAMOKU-DELLXPS-006',
        30,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['dell', 'xps', 'ultrabook', 'intel', 'premium'],
        '{"processor": "Intel Core i7-1360P", "memory": "16GB", "storage": "512GB SSD", "display": "13.4-inch InfinityEdge"}'::jsonb,
        4.5,
        567,
        145,
        true
    ),
    (
        'Nintendo Switch OLED',
        'Enhanced gaming experience with vibrant 7-inch OLED screen, improved audio, and 64GB internal storage.',
        349.00,
        379.00,
        ARRAY['https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'electronics',
        'gaming',
        'SAMOKU-NSW-007',
        60,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['nintendo', 'switch', 'gaming', 'oled', 'portable'],
        '{"screen_size": "7-inch OLED", "storage": "64GB", "battery": "4.5-9 hours", "modes": "TV, Tabletop, Handheld"}'::jsonb,
        4.8,
        3421,
        1876,
        true
    ),
    (
        'Apple Watch Series 9 GPS',
        'Most advanced Apple Watch with S9 chip, Double Tap gesture, and comprehensive health tracking.',
        399.00,
        429.00,
        ARRAY['https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'electronics',
        'wearables',
        'SAMOKU-AW9-008',
        80,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['apple', 'watch', 'smartwatch', 'health', 'fitness'],
        '{"chip": "S9 SiP", "display": "45mm Retina", "battery": "18 hours", "water_resistance": "50 meters"}'::jsonb,
        4.6,
        1567,
        789,
        true
    ),

    -- Fashion (7 products)
    (
        'Levi''s 501 Original Jeans',
        'Iconic straight-leg jeans with classic button fly, made from premium denim for lasting comfort and style.',
        89.00,
        98.00,
        ARRAY['https://images.pexels.com/photos/1598508/pexels-photo-1598508.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'fashion',
        'jeans',
        'SAMOKU-LEVIS501-009',
        120,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['levis', 'jeans', 'denim', 'classic', 'unisex'],
        '{"material": "100% Cotton", "fit": "Regular", "rise": "Mid", "care": "Machine wash cold"}'::jsonb,
        4.5,
        2876,
        1543,
        true
    ),
    (
        'Nike Air Max 270',
        'Revolutionary running shoes with Max Air heel unit for ultimate comfort and iconic street style.',
        149.00,
        170.00,
        ARRAY['https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'fashion',
        'shoes',
        'SAMOKU-NIKE270-010',
        95,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['nike', 'air-max', 'sneakers', 'running', 'comfort'],
        '{"upper": "Mesh and synthetic", "sole": "Rubber with Max Air", "weight": "300g", "sizes": "US 6-13"}'::jsonb,
        4.7,
        1876,
        967,
        true
    ),
    (
        'Adidas Ultraboost 22',
        'Energy-returning running shoes with responsive BOOST midsole and Primeknit upper for adaptive fit.',
        189.00,
        220.00,
        ARRAY['https://images.pexels.com/photos/1464625/pexels-photo-1464625.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'fashion',
        'shoes',
        'SAMOKU-ADIDAS22-011',
        70,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['adidas', 'ultraboost', 'running', 'boost', 'primeknit'],
        '{"midsole": "BOOST", "upper": "Primeknit", "outsole": "Continental Rubber", "drop": "10mm"}'::jsonb,
        4.6,
        1234,
        654,
        true
    ),
    (
        'Patagonia Better Sweater Jacket',
        'Warm and versatile fleece jacket made from recycled polyester with classic styling and all-day comfort.',
        139.00,
        159.00,
        ARRAY['https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'fashion',
        'outerwear',
        'SAMOKU-PATAGO-012',
        85,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['patagonia', 'fleece', 'jacket', 'outdoor', 'sustainable'],
        '{"material": "100% Recycled Polyester", "weight": "435g", "fit": "Regular", "pockets": "Two zippered hand pockets"}'::jsonb,
        4.8,
        967,
        432,
        true
    ),
    (
        'Ray-Ban Aviator Classic',
        'Iconic aviator sunglasses with crystal clear lenses and lightweight metal frame for timeless style.',
        169.00,
        189.00,
        ARRAY['https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'fashion',
        'accessories',
        'SAMOKU-RAYBAN-013',
        110,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['ray-ban', 'aviator', 'sunglasses', 'classic', 'luxury'],
        '{"lens": "Crystal Green", "frame": "Gold Metal", "protection": "100% UV", "size": "58mm"}'::jsonb,
        4.7,
        3456,
        2134,
        true
    ),
    (
        'Lululemon Align High-Rise Pants',
        'Buttery-soft yoga pants with four-way stretch and weightless feel for ultimate comfort during workouts.',
        128.00,
        148.00,
        ARRAY['https://images.pexels.com/photos/8436522/pexels-photo-8436522.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'fashion',
        'activewear',
        'SAMOKU-LULU-014',
        90,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['lululemon', 'align', 'yoga', 'leggings', 'athleisure'],
        '{"fabric": "Nulu", "rise": "High-rise", "inseam": "28 inches", "feel": "Weightless coverage"}'::jsonb,
        4.9,
        2345,
        1567,
        true
    ),
    (
        'Canada Goose Expedition Parka',
        'Arctic-ready expedition parka with premium down fill and fur-trimmed hood for extreme cold protection.',
        1095.00,
        1195.00,
        ARRAY['https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'fashion',
        'outerwear',
        'SAMOKU-CG-015',
        20,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['canada-goose', 'parka', 'winter', 'expedition', 'luxury'],
        '{"fill": "625 fill-power down", "temperature": "-25°C", "hood": "Coyote fur trim", "length": "Hip length"}'::jsonb,
        4.8,
        456,
        123,
        true
    ),

    -- Home & Kitchen (6 products)
    (
        'KitchenAid Artisan Stand Mixer',
        'Iconic stand mixer with 5-quart stainless steel bowl, 10 speeds, and planetary mixing action for perfect results.',
        449.00,
        499.00,
        ARRAY['https://images.pexels.com/photos/4686821/pexels-photo-4686821.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'home-kitchen',
        'appliances',
        'SAMOKU-KA-016',
        40,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['kitchenaid', 'mixer', 'baking', 'kitchen', 'appliance'],
        '{"capacity": "5 quarts", "speeds": "10", "power": "325 watts", "attachments": "Flat beater, dough hook, wire whip"}'::jsonb,
        4.8,
        1876,
        845,
        true
    ),
    (
        'Instant Pot Duo Plus 9-in-1',
        'Multi-functional electric pressure cooker that replaces 9 kitchen appliances with smart programming.',
        119.00,
        149.00,
        ARRAY['https://images.pexels.com/photos/4099355/pexels-photo-4099355.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'home-kitchen',
        'appliances',
        'SAMOKU-IP-017',
        65,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['instant-pot', 'pressure-cooker', 'multi-cooker', 'smart', 'kitchen'],
        '{"capacity": "6 quarts", "functions": "9-in-1", "programs": "13 Smart Programs", "safety": "10+ safety features"}'::jsonb,
        4.6,
        4567,
        2890,
        true
    ),
    (
        'All-Clad D3 Stainless Steel Cookware Set',
        'Professional-grade tri-ply stainless steel cookware set with superior heat distribution and durability.',
        599.00,
        699.00,
        ARRAY['https://images.pexels.com/photos/4226796/pexels-photo-4226796.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'home-kitchen',
        'cookware',
        'SAMOKU-ALLCLAD-018',
        25,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['all-clad', 'cookware', 'stainless-steel', 'professional', 'set'],
        '{"pieces": "10-piece set", "material": "Tri-ply stainless steel", "compatibility": "All cooktops", "care": "Dishwasher safe"}'::jsonb,
        4.9,
        678,
        234,
        true
    ),
    (
        'Dyson V15 Detect Cordless Vacuum',
        'Advanced cordless vacuum with laser dust detection and intelligent suction adjustment for deep cleaning.',
        749.00,
        849.00,
        ARRAY['https://images.pexels.com/photos/4246119/pexels-photo-4246119.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'home-kitchen',
        'appliances',
        'SAMOKU-DYSON-019',
        35,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['dyson', 'vacuum', 'cordless', 'laser', 'cleaning'],
        '{"battery": "60 minutes", "filtration": "HEPA", "bin_capacity": "0.76L", "weight": "3.1kg"}'::jsonb,
        4.7,
        1345,
        567,
        true
    ),
    (
        'Le Creuset Dutch Oven 5.5QT',
        'Iconic enameled cast iron Dutch oven perfect for slow cooking, braising, baking, and roasting.',
        349.00,
        399.00,
        ARRAY['https://images.pexels.com/photos/4198479/pexels-photo-4198479.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'home-kitchen',
        'cookware',
        'SAMOKU-LECREUSET-020',
        30,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['le-creuset', 'dutch-oven', 'cast-iron', 'enameled', 'french'],
        '{"capacity": "5.5 quarts", "material": "Enameled cast iron", "oven_safe": "500°F", "lifetime": "Lifetime warranty"}'::jsonb,
        4.9,
        987,
        445,
        true
    ),
    (
        'Vitamix 5200 Blender',
        'Professional-grade blender with aircraft-grade stainless steel blades and variable speed control.',
        449.00,
        549.00,
        ARRAY['https://images.pexels.com/photos/4439444/pexels-photo-4439444.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'home-kitchen',
        'appliances',
        'SAMOKU-VITAMIX-021',
        45,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['vitamix', 'blender', 'professional', 'smoothies', 'kitchen'],
        '{"motor": "2-peak HP", "container": "64 oz", "blades": "Aircraft-grade steel", "warranty": "7 years"}'::jsonb,
        4.8,
        1234,
        678,
        true
    ),

    -- Beauty (5 products)
    (
        'Fenty Beauty Pro Filt''r Foundation',
        'Soft matte longwear foundation with buildable coverage in 50 inclusive shades for all skin tones.',
        38.00,
        42.00,
        ARRAY['https://images.pexels.com/photos/4465124/pexels-photo-4465124.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'beauty',
        'makeup',
        'SAMOKU-FENTY-022',
        150,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['fenty', 'foundation', 'makeup', 'inclusive', 'long-wear'],
        '{"coverage": "Medium to full", "finish": "Soft matte", "shades": "50 shades", "size": "32ml"}'::jsonb,
        4.6,
        5678,
        3456,
        true
    ),
    (
        'The Ordinary Niacinamide 10% + Zinc 1%',
        'High-strength vitamin and mineral blemish formula to reduce the appearance of blemishes and congestion.',
        7.20,
        8.50,
        ARRAY['https://images.pexels.com/photos/3685538/pexels-photo-3685538.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'beauty',
        'skincare',
        'SAMOKU-ORDINARY-023',
        200,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['the-ordinary', 'niacinamide', 'skincare', 'serum', 'affordable'],
        '{"concentration": "10% Niacinamide", "additional": "1% Zinc PCA", "size": "30ml", "skin_type": "All types"}'::jsonb,
        4.4,
        8934,
        5672,
        true
    ),
    (
        'Drunk Elephant C-Firma Day Serum',
        'Potent vitamin C day serum with antioxidants and nutrient-rich fruit enzymes for firmer, brighter skin.',
        78.00,
        89.00,
        ARRAY['https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'beauty',
        'skincare',
        'SAMOKU-DE-024',
        75,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['drunk-elephant', 'vitamin-c', 'serum', 'antioxidant', 'premium'],
        '{"vitamin_c": "15% L-Ascorbic Acid", "size": "30ml", "ph": "3.3", "usage": "Morning only"}'::jsonb,
        4.7,
        2345,
        1234,
        true
    ),
    (
        'Charlotte Tilbury Pillow Talk Lipstick',
        'Iconic matte lipstick in universally flattering nude-pink shade with cashmere finish.',
        37.00,
        42.00,
        ARRAY['https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'beauty',
        'makeup',
        'SAMOKU-CT-025',
        180,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['charlotte-tilbury', 'lipstick', 'pillow-talk', 'nude', 'luxury'],
        '{"finish": "Matte", "shade": "Pillow Talk", "size": "3.5g", "formula": "Cashmere kiss"}'::jsonb,
        4.8,
        3456,
        2134,
        true
    ),
    (
        'Dyson Supersonic Hair Dryer',
        'Intelligent heat control hair dryer with fast drying and magnetic attachments for salon-quality results.',
        429.00,
        479.00,
        ARRAY['https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'beauty',
        'hair-care',
        'SAMOKU-DYSONH-026',
        50,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['dyson', 'hair-dryer', 'supersonic', 'professional', 'heat-control'],
        '{"motor": "Digital motor V9", "heat_damage": "Prevents extreme heat damage", "attachments": "5 magnetic attachments", "weight": "659g"}'::jsonb,
        4.7,
        1567,
        689,
        true
    ),

    -- Sports (4 products)
    (
        'Peloton Bike+',
        'Interactive fitness bike with rotating HD touchscreen, live and on-demand classes, and auto-resistance.',
        2495.00,
        2695.00,
        ARRAY['https://images.pexels.com/photos/416978/pexels-photo-416978.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'sports',
        'fitness',
        'SAMOKU-PELOTON-027',
        15,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['peloton', 'bike', 'fitness', 'interactive', 'premium'],
        '{"screen": "23.8-inch HD", "resistance": "Auto-Follow", "classes": "Live + On-Demand", "subscription": "Required"}'::jsonb,
        4.6,
        1876,
        234,
        true
    ),
    (
        'Yeti Rambler 30oz Tumbler',
        'Double-wall vacuum insulated tumbler that keeps drinks hot or cold for hours with leak-resistant lid.',
        38.00,
        45.00,
        ARRAY['https://images.pexels.com/photos/2181772/pexels-photo-2181772.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'sports',
        'outdoor',
        'SAMOKU-YETI-028',
        150,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['yeti', 'tumbler', 'insulated', 'outdoor', 'durable'],
        '{"capacity": "30 oz", "insulation": "Double-wall vacuum", "material": "18/8 stainless steel", "lid": "MagSlider"}'::jsonb,
        4.8,
        4567,
        2890,
        true
    ),
    (
        'Hydro Flask 32oz Water Bottle',
        'Insulated stainless steel water bottle that keeps beverages cold for 24 hours or hot for 12 hours.',
        44.95,
        49.95,
        ARRAY['https://images.pexels.com/photos/1000084/pexels-photo-1000084.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'sports',
        'outdoor',
        'SAMOKU-HYDRO-029',
        200,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['hydro-flask', 'water-bottle', 'insulated', 'eco-friendly', 'outdoor'],
        '{"capacity": "32 oz", "cold_retention": "24 hours", "hot_retention": "12 hours", "material": "18/8 Pro-Grade Steel"}'::jsonb,
        4.7,
        6789,
        4123,
        true
    ),
    (
        'Manduka PRO Yoga Mat',
        'Professional-grade yoga mat with superior cushioning, unmatched grip, and lifetime guarantee.',
        120.00,
        140.00,
        ARRAY['https://images.pexels.com/photos/863988/pexels-photo-863988.jpeg?auto=compress&cs=tinysrgb&w=500'],
        'sports',
        'fitness',
        'SAMOKU-MANDUKA-030',
        80,
        admin_user_id,
        admin_store_id,
        false,
        ARRAY['manduka', 'yoga-mat', 'professional', 'non-slip', 'eco-friendly'],
        '{"thickness": "6mm", "length": "71 inches", "width": "24 inches", "warranty": "Lifetime guarantee"}'::jsonb,
        4.8,
        2134,
        1345,
        true
    );

END $$;